name: Build and Publish

on:
  push:
    branches:
      - main
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout gotosocial into tmp
        uses: actions/checkout@v2
        with:
          repository: gotosocial/gotosocial
          path: ./gotosocial
          fetch-depth: 0
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Apply patches
        run: |
          cd gotosocial
          ls -la .
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git am ../patches/*.patch
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build go binaries
        run: |
          ./scripts/build.sh
        working-directory: ./gotosocial

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./gotosocial
          file: ./gotosocial/Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/thekitty-zone/custom-gotosocial:latest
